/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-04-07 14:50:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.object.TuVung;

public final class theodoi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1459737958069L));
    _jspx_dependants.put("/import.jsp", Long.valueOf(1459525403145L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1459388487048L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/ico\" href=\"favicon.ico\" /> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/Chart.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/Chart.min.js\" ></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/js/src/Chart.Line.js\" ></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link  rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/all.css\" >\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<title>Theo dõi</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table#tuvung {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tcolor: blue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.linktuvung {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #3b5998;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a.linktuvung:HOVER {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".xoa{\r\n");
      out.write("\tvisibility:hidden\r\n");
      out.write("}\r\n");
      out.write(".nghia{\r\n");
      out.write("\tvisibility:hidden\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".display{\r\n");
      out.write("\tvisibility:visible;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hienthixoa{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#hienthinghia{\r\n");
      out.write("\twidth: 105px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head> \r\n");
      out.write("<style>\r\n");
      out.write("ul {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    border: 1px solid #e7e7e7;\r\n");
      out.write("    background-color: #f3f3f3;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("li {\r\n");
      out.write(" \tfloat: left; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    color: #666;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 5px 10px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a:hover:not(.active) {\r\n");
      out.write("    background-color: #ddd;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a.active {\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<ul>\r\n");
      out.write("  <li><a id=\"home\"  href=\"");
      out.print(request.getContextPath());
      out.write("\">Home</a></li> \r\n");
      out.write("  <li><a id=\"anhviet\" href=\"");
      out.print(request.getContextPath());
      out.write("/anhviet\">Anh-Việt</a></li>\r\n");
      out.write("  <li><a id=\"vietanh\" href=\"");
      out.print(request.getContextPath());
      out.write("/vietanh\">Việt-Anh</a></li>\r\n");
      out.write("  <li><a id=\"chitiet\" href=\"");
      out.print(request.getContextPath());
      out.write("/chitiet\">Chi tiết</a></li>\r\n");
      out.write("  <li><a id=\"toeic600\" href=\"");
      out.print(request.getContextPath());
      out.write("/toeic600\">Toeic 600</a></li>\r\n");
      out.write("  <li><a id=\"macdinh\" href=\"");
      out.print(request.getContextPath());
      out.write("/macdinh\">Cài đặt mặc định</a></li>\r\n");
      out.write("  <li><a id=\"homnay\" href=\"");
      out.print(request.getContextPath());
      out.write("/homnay\">Hôm nay</a></li>\r\n");
      out.write("  <li><a id=\"homqua\" href=\"");
      out.print(request.getContextPath());
      out.write("/homqua\">Hôm qua</a></li>\r\n");
      out.write("  <li><a id=\"homkia\" href=\"");
      out.print(request.getContextPath());
      out.write("/homkia\">Hôm kia</a></li>\r\n");
      out.write("  \r\n");
      out.write("  <li><a id=\"fibonaci\" href=\"");
      out.print(request.getContextPath());
      out.write("/fibonaci\">Fibonaci</a></li>\r\n");
      out.write("  <li><a id=\"theodoi\" href=\"");
      out.print(request.getContextPath());
      out.write("/theodoi\">Theo dõi</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write(" \r\n");
      out.write("\t<hr>\r\n");
      out.write("\t\t");
long homnay =  Long.parseLong((String)request.getAttribute("homnay"));
		long homqua =  Long.parseLong((String)request.getAttribute("homqua"));
		long homkia =  Long.parseLong((String)request.getAttribute("homkia"));
		long homkiaf =  Long.parseLong((String)request.getAttribute("homkiaf"));
		long homkiax =  Long.parseLong((String)request.getAttribute("homkiax"));
		long homkiar =  Long.parseLong((String)request.getAttribute("homkiar"));
		long homkiaj =  Long.parseLong((String)request.getAttribute("homkiaj"));
		
      out.write("\r\n");
      out.write("\t<canvas id=\"myChart\" width=\"1100px\" height=\"400px\"></canvas>\r\n");
      out.write("\t<hr>\r\n");
      out.write("\t ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\tfoooter\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
 request.removeAttribute("listTuVung") ;
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$(\"#theodoi\").addClass(\"active\");\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t$(\"#hienthinghia\").click(function() {\r\n");
      out.write("\t\t\t\t$(\".nghia\").toggleClass(\"display\");\r\n");
      out.write("\t\t\t\t$('#hienthinghia').html()===\"Hiển thị nghĩa\"?$('#hienthinghia').html(\"Tắt nghĩa\"):$('#hienthinghia').html(\"Hiển thị nghĩa\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#hienthixoa\").click(function() {\r\n");
      out.write("\t\t\t\t$(\".xoa\").toggleClass(\"display\");\r\n");
      out.write("\t\t\t\t$('#hienthixoa').html()===\"Hiển thị xóa\"?$('#hienthixoa').html(\"Tắt xóa\"):$('#hienthixoa').html(\"Hiển thị xóa\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar data = {\r\n");
      out.write("\t\t\t\t    labels: [\"Hôm kịa\", \"Hôm kỉa\", \"Hôm kĩa\", \"Hôm kìa\", \"Hôm kia\", \"Hôm qua\", \"Hôm nay\"],\r\n");
      out.write("\t\t\t\t    datasets: [ \r\n");
      out.write("\t\t\t\t        {\r\n");
      out.write("\t\t\t\t            label: \"My Second dataset\",\r\n");
      out.write("\t\t\t\t            fillColor: \"rgba(151,187,205,0.2)\",\r\n");
      out.write("\t\t\t\t            strokeColor: \"rgba(0,0,255,1)\",\r\n");
      out.write("\t\t\t\t            pointColor: \"rgba(0,0,255,1)\",\r\n");
      out.write("\t\t\t\t            pointStrokeColor: \"#fff\",\r\n");
      out.write("\t\t\t\t            pointHighlightFill: \"#fff\",\r\n");
      out.write("\t\t\t\t            pointHighlightStroke: \"rgba(0,0,255,1)\",\r\n");
      out.write("\t\t\t\t            data: [");
      out.print(homkiaj );
      out.write(',');
      out.write(' ');
      out.print(homkiar );
      out.write(',');
      out.write(' ');
      out.print(homkiax );
      out.write(',');
      out.write(' ');
      out.print(homkiaf );
      out.write(',');
      out.write(' ');
      out.print(homkia );
      out.write(',');
      out.write(' ');
      out.print(homqua );
      out.write(',');
      out.write(' ');
      out.print(homnay );
      out.write("]\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t    ]\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\tvar ctx = document.getElementById(\"myChart\").getContext(\"2d\");\r\n");
      out.write("\t\t\tvar myLineChart = new Chart(ctx).Line(data, {\r\n");
      out.write("\t\t\t    bezierCurve: false,\r\n");
      out.write("\t\t\t    scaleFontColor: \"#0000ff\",\r\n");
      out.write("\t\t\t    scaleFontSize: 13,\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction xoa(id) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t    url: '");
      out.print(request.getContextPath());
      out.write("/anhviet',\r\n");
      out.write("\t\t\t    data: \"ma=xoa&&id=\"+ id,\r\n");
      out.write("\t\t\t    type: 'post',\r\n");
      out.write("\t\t\t    dataType:'text',\r\n");
      out.write("\t\t\t    success: function(data){ \r\n");
      out.write("\t\t\t    \twindow.location.href = \"/engreview/anhviet\"; \r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
